name: Test

on:
  push:
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.15.0
          run_install: false

      - name: Set Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm install --no-frozen-lockfile
      - run: pnpm build
      - run: pnpm test:coverage

  vite-compat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.15.0
          run_install: false

      - name: Set Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm install --no-frozen-lockfile
      - run: pnpm test:compat
